runtime: nodejs18

instance_class: F2

service: coleccionista-web

env_variables:
  PORT: 8080

handlers:
- url: /(.*\.(gif|png|jpg|css|js|svg|json))
  static_files: dist/\1
  upload: dist/(.*\.(gif|png|jpg|css|js|svg|json))
  secure: always
  redirect_http_response_code: 301

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
  redirect_http_response_code: 301

